### PR TITLE
Implement builder pattern

### PR DESCRIPTION
**Pull request by michaeldev5**
To make SDK easier to use builder pattern was implemented in the file `Builder.ts`. From an implementation point of view, the "Builder with a twist" design pattern also known as "Step builder" was specifically chosen because of the large number of mandatory fields. In short this pattern uses the common builder pattern, but adds a twist by using interface to force which value to set next and thereby solving the problem with many mandatory values. 

Builder pattern supports following use cases: 
- Transfer tokens from parachain to parachain
- Transfer tokens from relaychain to parachain
- Transfer tokens from parachain to relaychain
- Open a channel
- Close a channel

To use Builder API, developer first imports a `Builder` function as follows:

`
import { Builder } from '@paraspell/sdk'
`

Builder function accepts one parameter of type `ApiPromise`. Then, other functions can be chained depending on the use case. In the case of initiating a token transfer the Builder class decides which scenario to use depending on the `from()` and `to()` methods. Depending on the scenario different mandatory fields are required. Every step of the build process is properly typed and therefore invalid object cannot be created. After providing all required parameters the `build()` method executes the transaction or open/closes a channel. Mandatory fields must be specified in the same order as they are shown in the example otherwise typescript error will be generated.

### Developer experience
When developing, the developer is guided by the typescript and thus knows which parameter can be added as next. This increases the developer experience and makes SDK easier to use.
Screenshot 2023-01-08 at 14 27 53

Other changes:
- Unit tests for each use case are written in the file `Builder.test.ts`. unit tests are designed in such a way that they check the parameters of the target function, which each case of using the builder pattern calls when `build()` method is executed. This is achieved by the spy function from vitest.

#### Transfer tokens from parachain to parachain
Both `from` and `to` parameters are provided, thus the parachain to parachain scenario will be used.

```
  Builder(api)
      .from('Acala')
      .to('Quartz')
      .currency('ACA')
      .currencyId(currencyId)
      .amount(amount)
      .address(address)
      .build()
```

#### Transfer tokens from relaychain to parachain
Only `from` parameter is provided, thus the relaychain to parachain scenario will be used.

```
  Builder(api)
      .to('Acala')
      .amount(amount)
      .address(address)
      .build()
```

#### Transfer tokens from parachain to relaychain
Only `to` parameter is provided, thus the parachain to relaychain scenario will be used.

```
    Builder(api)
      .from('Acala')
      .currency('ACA')
      .currencyId(currencyId)
      .amount(amount)
      .address(address)
      .build()
```

#### Open a channel
When opening a new channel the operation has to be specified by calling `openChannel()` method and then providing `maxSize` and `maxMessageSize` parameters.

```
    Builder(api)
      .from('Acala')
      .to('Quartz')
      .openChannel()
      .maxSize(maxSize)
      .maxMessageSize(maxMsgSize)
      .build()
```

#### Close a channel
When opening a new channel the operation has to be specified by calling `closeChannel()` method and then providing `inbound` and `outbound` parameters.
```
    Builder(api)
      .from('Acala')
      .closeChannel()
      .inbound(inbound)
      .outbound(outbound)
      .build()
```

### CODE REVIEW

**Review by dudo50 — APPROVED** [review]

**Comment by vikiival** [comment]
Nice job!

Wondering why you need both currency and currencyId?

**Comment by dudo50** [comment]
@vikiival some nodes require asset symbols and some asset ids. This way user can enter ones that their node supports. However this is good point and I am gling to create new issue covering this.

**Comment by dudo50** [comment]
@vikiival some nodes require asset symbols and some asset ids. This way user can enter ones that their node supports. However this is good point and I am going to create new issue covering this.

**Comment by dudo50** [comment]
@vikiival some nodes require asset symbols and some asset ids. This way user can enter ones that their node supports. However this is good point and I am going to create new issue covering this.

**Pull request merged**
